# Generated by Django 6.0.6 on 2026-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_created_at_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchi profillari'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Laboratoriya nomi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('chemist', 'Kimyogar'), ('laborant', 'Laborant'), ('viewer', 'Kuzatuvchi')], default='viewer', max_length=20, verbose_name='Rol'),
        ),
    ]
