# Generated by Django 6.0.6 on 2026-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="O'zbekcha nomi")),
                ('name_iupac', models.CharField(max_length=255, verbose_name='IUPAC nomi')),
                ('cas_number', models.CharField(max_length=20, unique=True, verbose_name='CAS raqami')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('mg', 'Milligram'), ('ml', 'Millilitr'), ('l', 'Litr'), ('mol', 'Mol')], max_length=10, verbose_name="O'lchov birligi")),
                ('min_threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum chegara')),
                ('expiry_date', models.DateField(verbose_name='Muddati tugash sanasi')),
                ('hazard_level', models.IntegerField(choices=[(1, 'Past xavf'), (2, "O'rta xavf"), (3, 'Yuqori xavf'), (4, 'Juda yuqori xavf')], verbose_name='Xavflilik darajasi')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Etkazib beruvchi')),
                ('storage_condition', models.CharField(blank=True, max_length=255, verbose_name='Saqlash sharoiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
