# Generated by Django 6.0.6 on 2026-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'verbose_name': 'Kimyoviy modda', 'verbose_name_plural': 'Kimyoviy moddalar'},
        ),
        migrations.AddField(
            model_name='chemical',
            name='formula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kimyoviy formula'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
    ]
