# Generated by Django 6.0.6 on 2026-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_chemical_options_chemical_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
