# Generated by Django 6.0.6 on 2026-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_chemical_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'ordering': ['name_uz'], 'verbose_name': 'Kimyoviy modda', 'verbose_name_plural': 'Kimyoviy moddalar'},
        ),
        migrations.AlterField(
            model_name='chemical',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
    ]
