# Generated by Django 6.0.6 on 2026-06-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Namuna nomi')),
                ('source_type', models.CharField(choices=[('industrial', 'Sanoat'), ('field', 'Dala'), ('medical', 'Tibbiy'), ('educational', "O'quv")], max_length=20, verbose_name='Manba turi')),
                ('status', models.CharField(choices=[('received', 'Qabul qilindi'), ('in_progress', 'Tahlil jarayonida'), ('completed', 'Tugallandi'), ('archived', 'Arxivlandi')], default='received', max_length=20, verbose_name='Holat')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori')),
                ('unit', models.CharField(max_length=10, verbose_name="O'lchov birligi")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Qabul sanasi')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='users.userprofile', verbose_name='Qabul qilgan')),
            ],
            options={
                'verbose_name': 'Namuna',
                'verbose_name_plural': 'Namunalar',
                'ordering': ['-received_at'],
            },
        ),
    ]
