# Generated by Django 6.0.6 on 2026-06-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Namuna nomi'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izohlar'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Namuna ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('mg', 'Milligram'), ('ml', 'Millilitr'), ('l', 'Litr')], max_length=10, verbose_name="O'lchov birligi"),
        ),
        migrations.CreateModel(
            name='SampleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='samples.sample')),
            ],
            options={
                'verbose_name': 'Status tarixi',
                'verbose_name_plural': 'Status tarixi',
                'ordering': ['-changed_at'],
            },
        ),
    ]
